In [1]:
#Question1
import pandas as pd
data = [[10, 90, 85, 1, 100, 1],
        [5, 60, 70, 0, 80, 0],
        [15, 95, 90, 1, 100, 1],
        [2, 30, 50, 0, 40, 0],
        [12, 85, 88, 1, 90, 1],
        [8, 75, 65, 0, 70, 0],
        [14, 92, 93, 1, 95, 1],
        [3, 50, 55, 0, 60, 0],
        [11, 88, 80, 1, 85, 1],
        [6, 65, 60, 0, 75, 0]]
df = pd.DataFrame(data, columns=['Study Hours per Week', 'Class Attendance (%)', 'Previous Exam Score (%)', 'Participation in Group Study', 'Submission of Assignments (%)', 'Pass/Fail'])
df

Study Hours per Week  Class Attendance (%)  Previous Exam Score (%)  \
0                    10                    90                       85   
1                     5                    60                       70   
2                    15                    95                       90   
3                     2                    30                       50   
4                    12                    85                       88   
5                     8                    75                       65   
6                    14                    92                       93   
7                     3                    50                       55   
8                    11                    88                       80   
9                     6                    65                       60   

   Participation in Group Study  Submission of Assignments (%)  Pass/Fail  
0                             1                            100          1  
1                             0                             80          0  
2                             1                            100          1  
3                             0                             40          0  
4                             1                             90          1  
5                             0                             70          0  
6                             1                             95          1  
7                             0                             60          0  
8                             1                             85          1  
9                             0                             75          0

In [2]:
df.to_csv('student_data.csv', index=False)
df

Study Hours per Week  Class Attendance (%)  Previous Exam Score (%)  \
0                    10                    90                       85   
1                     5                    60                       70   
2                    15                    95                       90   
3                     2                    30                       50   
4                    12                    85                       88   
5                     8                    75                       65   
6                    14                    92                       93   
7                     3                    50                       55   
8                    11                    88                       80   
9                     6                    65                       60   

   Participation in Group Study  Submission of Assignments (%)  Pass/Fail  
0                             1                            100          1  
1                             0                             80          0  
2                             1                            100          1  
3                             0                             40          0  
4                             1                             90          1  
5                             0                             70          0  
6                             1                             95          1  
7                             0                             60          0  
8                             1                             85          1  
9                             0                             75          0

In [3]:
x = df.drop('Pass/Fail', axis=1)
y = df['Pass/Fail']

In [4]:
import numpy as np
list=[2.0,3.0,7.0,1.0,5.0]
weight = np.array(list)
weight

array([2., 3., 7., 1., 5.])

In [5]:
def update(p,e,i):
  for j in range(len(weight)):
    weight[j]=weight[j]+p*e*float(x.iloc[i:i+1,j:j+1].values)
print(x.iloc[0:1,1:2])

   Class Attendance (%)
0                    90


In [6]:
learning_rate = 0.001
def error(yp,i):
  e=y[i]-yp
  if(e!=0):
    update(learning_rate,e,i)

yp=-1
import numpy as np
for k in range(6):
  for i in range (len(x)):
    z=np.dot(x[i:i+1],weight)
    if z>0:
      yp=1
    else:
      yp=0
    error(yp,i)
   # print(weight)

<ipython-input-5-2679864f734e>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  weight[j]=weight[j]+p*e*float(x.iloc[i:i+1,j:j+1].values)


In [7]:
print("Trained Weights:", weight)

# Prediction Function
def perceptron_predict(x, weights):
    z = np.dot(x, weights)
    return 1 if z >= 0 else 0

# Test the model
correct_predictions = 0
for i in range(len(x)):
    prediction = perceptron_predict(x[i:i+1], weight)
    if prediction == y[i]:
        correct_predictions += 1

# Accuracy calculation
accuracy = correct_predictions / len(x)
print(f"Accuracy: {accuracy * 100:.2f}%")

Trained Weights: [1.856 1.32  5.2   1.    3.05 ]
Accuracy: 50.00%


In [9]:
#Question2
import pandas as pd
diabetes=pd.read_csv('/content/ STML-06(2 ques) dataset.csv')
diabetes.head()

Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0   40   Male       No        Yes                 No      Yes         No   
1   58   Male       No         No                 No      Yes         No   
2   41   Male      Yes         No                 No      Yes        Yes   
3   45   Male       No         No                Yes      Yes        Yes   
4   60   Male      Yes        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      Yes     Yes  Positive  
1             Yes               No      Yes      No  Positive  
2              No              Yes      Yes      No  Positive  
3              No               No       No      No  Positive  
4             Yes              Yes      Yes     Yes  Positive

In [10]:
target_var=diabetes['class']
target_var.head()

0    Positive
1    Positive
2    Positive
3    Positive
4    Positive
Name: class, dtype: object

In [11]:
features=diabetes.drop('class',axis=1)
features.head()

Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0   40   Male       No        Yes                 No      Yes         No   
1   58   Male       No         No                 No      Yes         No   
2   41   Male      Yes         No                 No      Yes        Yes   
3   45   Male       No         No                Yes      Yes        Yes   
4   60   Male      Yes        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   

  partial paresis muscle stiffness Alopecia Obesity  
0              No              Yes      Yes     Yes  
1             Yes               No      Yes      No  
2              No              Yes      Yes      No  
3              No               No       No      No  
4             Yes              Yes      Yes     Yes

In [12]:
one_values = ["Male", "Yes"]
zero_values = ["Female","No"]

for column in features.columns:
    features[column] = features[column].replace(to_replace=one_values, value=1)
    features[column] = features[column].replace(to_replace=zero_values, value=0)
features

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0     40       1         0           1                   0         1   
1     58       1         0           0                   0         1   
2     41       1         1           0                   0         1   
3     45       1         0           0                   1         1   
4     60       1         1           1                   1         1   
..   ...     ...       ...         ...                 ...       ...   
515   39       0         1           1                   1         0   
516   48       0         1           1                   1         1   
517   58       0         1           1                   1         1   
518   32       0         0           0                   0         1   
519   42       1         0           0                   0         0   

     Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0             0               0                0        1             0   
1             0               0                1        0             0   
2             1               0                0        1             0   
3             1               1                0        1             0   
4             1               0                1        1             1   
..          ...             ...              ...      ...           ...   
515           1               0                0        1             0   
516           1               0                0        1             1   
517           1               0                1        0             0   
518           0               0                1        1             0   
519           0               0                0        0             0   

     delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  
0                  1                0                 1         1        1  
1                  0                1                 0         1        0  
2                  1                0                 1         1        0  
3                  1                0                 0         0        0  
4                  1                1                 1         1        1  
..               ...              ...               ...       ...      ...  
515                1                1                 0         0        0  
516                1                1                 0         0        0  
517                0                1                 1         0        1  
518                1                0                 0         1        0  
519                0                0                 0         0        0  

[520 rows x 16 columns]

In [13]:
one_values = ["Positive"]
zero_values = ["Negative"]

target_var = target_var.replace(to_replace=one_values, value=1)
target_var= target_var.replace(to_replace=zero_values, value=0)
target_var.head()

0    1
1    1
2    1
3    1
4    1
Name: class, dtype: int64

In [14]:
import numpy as np

list1 = [0.21, 0.60, 0.78, 0.22, 0.62 ,
       0.53, 0.39, 0.036, 0.04 , 0.87,
       0.89, 0.13, 0.79, 0.13, 0.50,
       0.80]
weights=np.array(list1)
weights

array([0.21 , 0.6  , 0.78 , 0.22 , 0.62 , 0.53 , 0.39 , 0.036, 0.04 ,
       0.87 , 0.89 , 0.13 , 0.79 , 0.13 , 0.5  , 0.8  ])

In [15]:
features.iloc[0:1].values

array([[40,  1,  0,  1,  0,  1,  0,  0,  0,  1,  0,  1,  0,  1,  1,  1]])

In [16]:
def update(p,e,i):
  for j in range(len(weights)):
    weights[j]=weights[j]+p*e*float(features.iloc[i:i+1,j:j+1].values)

In [17]:
learning_rate = 0.001
def error(yp,i):
  e=target_var[i]-yp
  if(e!=0):
    update(learning_rate,e,i)
  return cp

In [18]:
learning_rate = 0.001
def error(yp,i):
  e=target_var[i]-yp
  if(e!=0):
    update(learning_rate,e,i)
  return e # Changed cp to e

In [19]:
weights

array([0.21 , 0.6  , 0.78 , 0.22 , 0.62 , 0.53 , 0.39 , 0.036, 0.04 ,
       0.87 , 0.89 , 0.13 , 0.79 , 0.13 , 0.5  , 0.8  ])

In [20]:
print("Trained Weights:", weights)

# Prediction Function
def perceptron_predict(x, weights):
    z = np.dot(x, weights)
    return 1 if z >= 0 else 0

# Test the model
correct_predictions = 0
for i in range(len(features)):
    prediction = perceptron_predict(features[i:i+1], weights)
    if prediction == target_var[i]:
        correct_predictions += 1

# Accuracy calculation
accuracy = correct_predictions / len(features)
print(f"Accuracy: {accuracy * 100:.2f}%")

Trained Weights: [0.21  0.6   0.78  0.22  0.62  0.53  0.39  0.036 0.04  0.87  0.89  0.13
 0.79  0.13  0.5   0.8  ]
Accuracy: 61.54%
